[package]
name = "zqa"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "6.0.0"
arrow-array = "52.2.0"
arrow-schema = "52.2.0"
libsqlite3-sys = "^0.32"
rusqlite = "0.34.0"
dotenv = "0.15.0"
rag = { path = "../rag/"}
reqwest = "0.12.14"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.44.1"

[[bin]]
name = "zqa"
path = "src/chain.rs"
